// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKBgP_vAFAKv3Oirk923wktGdlyzt0EAQ',
    appId: '1:206205698312:web:1715aad8613d25c3816cbd',
    messagingSenderId: '206205698312',
    projectId: 'app-projects-ad5fa',
    authDomain: 'app-projects-ad5fa.firebaseapp.com',
    databaseURL: 'https://app-projects-ad5fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-projects-ad5fa.firebasestorage.app',
    measurementId: 'G-6G1LJ36VLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdSLIQ-YlYGJudp1xkSFuWGtqY4q48E7U',
    appId: '1:206205698312:android:99a01c2742710195816cbd',
    messagingSenderId: '206205698312',
    projectId: 'app-projects-ad5fa',
    databaseURL: 'https://app-projects-ad5fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-projects-ad5fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIoPXzwiixNrYprlE2SOy5OoPrJh5v82E',
    appId: '1:206205698312:ios:d51f5ab0f585b20b816cbd',
    messagingSenderId: '206205698312',
    projectId: 'app-projects-ad5fa',
    databaseURL: 'https://app-projects-ad5fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-projects-ad5fa.firebasestorage.app',
    iosBundleId: 'com.example.emergence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIoPXzwiixNrYprlE2SOy5OoPrJh5v82E',
    appId: '1:206205698312:ios:d51f5ab0f585b20b816cbd',
    messagingSenderId: '206205698312',
    projectId: 'app-projects-ad5fa',
    databaseURL: 'https://app-projects-ad5fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-projects-ad5fa.firebasestorage.app',
    iosBundleId: 'com.example.emergence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKBgP_vAFAKv3Oirk923wktGdlyzt0EAQ',
    appId: '1:206205698312:web:25dfc25fd9409377816cbd',
    messagingSenderId: '206205698312',
    projectId: 'app-projects-ad5fa',
    authDomain: 'app-projects-ad5fa.firebaseapp.com',
    databaseURL: 'https://app-projects-ad5fa-default-rtdb.firebaseio.com',
    storageBucket: 'app-projects-ad5fa.firebasestorage.app',
    measurementId: 'G-1ZWD6RY262',
  );
}
